"use client";

import { useMemo, useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import {
  buildPairs,
  buildSpheres,
  minClearance,
  type Clearance,
} from "@/lib/gen3-collision";
import {
  GRIPPER,
  GRIPPER_YAW,
  JOINT_FRAMES,
  JOINT_ORDER,
  MM,
  TOOL_FACE_Z,
  clampJoint,
  type JointKey,
} from "@/lib/gen3-kinematics";
import { Shell } from "./ArmStyle";

/**
 * The real Kinova Gen3 6-DOF (no-vision) with a Robotiq 2F-85, tessellated from
 * the vendor STEP files.
 *
 * Geometry comes from public/models/gen3.glb, generated by
 * scripts/build-gen3-glb.mjs. Every link mesh is already re-origined so its own
 * joint sits at (0,0,0), so each group below carries a constant offset and a
 * single rotation and nothing else. That is the whole point of the arrangement:
 * a link physically cannot translate, skew or pick up a second degree of
 * freedom, because there is nowhere in the tree to express one.
 *
 * Rotations are clamped to the actuator limits on every frame, so a caller
 * cannot drive the arm past what the hardware allows no matter what it puts in
 * the pose.
 */

const MODEL = "/models/gen3.glb";

export interface ArmPose {
  baseRoll: number;
  shoulderPitch: number;
  elbowPitch: number;
  wristRoll: number;
  wristPitch: number;
  toolRoll: number;
  /** 0 = fully open, 1 = fully closed. */
  grip: number;
}

export function createArmPose(): ArmPose {
  return {
    baseRoll: 0,
    shoulderPitch: 0.32,
    elbowPitch: 0.84,
    wristRoll: 0,
    wristPitch: 0.5,
    toolRoll: 0,
    grip: 0.2,
  };
}

type Vec3 = [number, number, number];

/**
 * CAD-space vector to scene-space, matching the build script.
 *
 * CAD is Z-up millimetres, the scene is Y-up scaled units, and the cyclic swap
 * cad(x,y,z) -> scene(y, z, x) that gets between them also lands the arm's only
 * two joint axes on the scene's own: CAD Z (the roll joints) becomes scene Y,
 * CAD Y (the pitch joints) becomes scene X. Every joint is then a positive
 * rotation about a scene axis, with no sign corrections anywhere.
 */
const toScene = (x: number, y: number, z: number): Vec3 => [y * MM, z * MM, x * MM];

/** Offset from one joint to the next, in the parent joint's own frame. */
function offsetBetween(parent: JointKey | null, child: JointKey | null): Vec3 {
  const p = parent ? JOINT_FRAMES[parent].origin : [0, 0, 0];
  const c = child ? JOINT_FRAMES[child].origin : [0, 0, 0];
  return toScene(c[0] - p[0], c[1] - p[1], c[2] - p[2]);
}

/** The tool face sits ahead of the last roll joint, on its axis. */
const TOOL_OFFSET: Vec3 = toScene(0, 0, TOOL_FACE_Z - JOINT_FRAMES.toolRoll.origin[2]);

/**
 * 2F-85 pivots in the gripper's own frame, as magnitudes.
 *
 * The CAD constants describe the jaw on the -X side. Storing |x| here lets one
 * `sign` build either jaw, which is much clearer than scaling a group by -1:
 * a negative scale flips triangle winding and turns the inverted-hull outline
 * inside out.
 */
const G = (() => {
  const v = (p: readonly [number, number]): Vec3 => [Math.abs(p[0]) * MM, p[1] * MM, 0];
  const sub = (a: Vec3, b: Vec3): Vec3 => [a[0] - b[0], a[1] - b[1], 0];
  const knuckle = v(GRIPPER.outerKnuckle);
  const finger = v(GRIPPER.outerFinger);
  const tip = v(GRIPPER.innerFinger);
  return {
    knuckle,
    innerKnuckle: v(GRIPPER.innerKnuckle),
    /** Outer finger, relative to the knuckle it is bolted to. */
    finger: sub(finger, knuckle),
    /** Inner finger, relative to the outer finger. */
    tip: sub(tip, finger),
  };
})();

/**
 * Which way each gripper group turns as the jaws close, about the gripper's Z.
 *
 * Closing swings both knuckles toward the centreline, so their sense is the
 * side's own sign; the inner fingers take the opposite, which is what holds the
 * pads parallel through the stroke.
 */
const JAW_SENSE: Array<[string, number]> = [
  ["knuckleL", -1],
  ["innerKnuckleL", -1],
  ["tipL", 1],
  ["knuckleR", 1],
  ["innerKnuckleR", 1],
  ["tipR", -1],
];

/** Every mesh the glb is expected to contain, in chain order. */
const LINK_KEYS = [
  "base",
  "shoulder",
  "bicep",
  "forearm",
  "wrist1",
  "wrist2",
  "tool",
  "palm",
  ...(["L", "R"] as const).flatMap((s) => [
    `knuckle${s}`,
    `finger${s}`,
    `tip${s}`,
    `pad${s}`,
    `innerKnuckle${s}`,
  ]),
];

/** Every group that rotates: the six joints, plus the gripper's six followers. */
const GROUP_KEYS = [...JOINT_ORDER, ...JAW_SENSE.map(([key]) => key)];

/**
 * Scene-graph name of the group that drives a joint.
 *
 * Pivots are prefixed because a jaw's group and the mesh it carries share a
 * name otherwise, and getObjectByName returns whichever it reaches first.
 */
const pivot = (key: string) => `pivot:${key}`;

type GLTFNodes = Record<string, THREE.Mesh | undefined>;

export interface Gen3ArmProps {
  pose: ArmPose;
  /**
   * Reports the closest approach between links that should never meet.
   *
   * Off by default, and worth leaving off: it is for tools that let a human
   * drive the joints anywhere, like the lab. The hero's own motion is checked
   * offline instead, by sweeping the whole idle envelope in
   * scripts/check-gen3-glb.mjs, so it does not need to pay for this per frame.
   */
  onClearance?: (clearance: Clearance) => void;
}

export default function Gen3Arm({ pose, onClearance }: Gen3ArmProps) {
  const { nodes } = useGLTF(MODEL) as unknown as { nodes: GLTFNodes };
  const root = useRef<THREE.Group>(null);
  /**
   * Every group and mesh the frame loop touches, looked up once by name.
   *
   * One ref on the root rather than two dozen scattered through the tree: the
   * chain below is deep and mostly built by helpers, so threading a ref to each
   * level would be far more code than a single resolve pass, and it would have
   * to be kept in step by hand every time a link moved.
   */
  const parts = useRef<{
    groups: Record<string, THREE.Object3D>;
    links: Record<string, THREE.Object3D>;
  } | null>(null);

  const collision = useMemo(() => {
    if (!onClearance) return null;
    const keys = LINK_KEYS.filter((key) => nodes[key]?.geometry);
    const spheres = keys.map((key) =>
      buildSpheres(nodes[key]!.geometry, { scale: nodes[key]!.scale.x }),
    );
    return { keys, spheres, pairs: buildPairs(keys) };
  }, [nodes, onClearance]);

  useFrame(() => {
    const scene = root.current;
    if (!scene) return;
    if (!parts.current) {
      const find = (keys: string[], name: (k: string) => string) =>
        Object.fromEntries(
          keys.flatMap((key) => {
            const object = scene.getObjectByName(name(key));
            return object ? [[key, object] as const] : [];
          }),
        );
      parts.current = {
        groups: find(GROUP_KEYS, pivot),
        links: find(LINK_KEYS, (k) => k),
      };
    }
    const { groups, links: meshes } = parts.current;

    for (const key of JOINT_ORDER) {
      const group = groups[key];
      if (!group) continue;
      const angle = clampJoint(key, pose[key]);
      // CAD Z is scene Y and CAD Y is scene X, per toScene. No joint ever
      // writes more than one of these.
      if (JOINT_FRAMES[key].axis === "z") group.rotation.y = angle;
      else group.rotation.x = angle;
    }

    // One driven angle for the whole gripper, exactly as the real 2F-85 has one
    // motor. Everything else is the four-bar following it.
    const theta = Math.min(1, Math.max(0, pose.grip)) * GRIPPER.thetaMax;
    for (const [key, sense] of JAW_SENSE) {
      const group = groups[key];
      if (group) group.rotation.z = theta * sense;
    }

    if (!onClearance || !collision) return;
    // The rotations above only reach matrixWorld when three walks the graph at
    // render time, which is after every useFrame. Force it here so the answer
    // describes the pose just written rather than the previous frame's.
    scene.updateMatrixWorld(true);
    const links = collision.keys.flatMap((key, i) => {
      const object = meshes[key];
      return object ? [{ key, object, spheres: collision.spheres[i] }] : [];
    });
    if (links.length === collision.keys.length) {
      onClearance(minClearance(links, collision.pairs));
    }
  });

  /**
   * A link mesh, or nothing if the glb predates it.
   *
   * The shell inherits the glTF node's own transform, which is not decoration:
   * the build quantizes positions to int16 and KHR_mesh_quantization carries
   * the dequantization as a per-node scale and offset. Handing the raw geometry
   * to a fresh mesh at identity would draw every link at its own wrong size.
   */
  const link = (key: string, threshold = 22) => {
    const node = nodes[key];
    if (!node?.geometry) return null;
    return (
      <Shell
        name={key}
        geometry={node.geometry}
        position={node.position}
        quaternion={node.quaternion}
        scale={node.scale}
        threshold={threshold}
      />
    );
  };

  /** One jaw of the 2F-85. `side` is -1 for the jaw on the -X side. */
  const jaw = (side: 1 | -1) => {
    const s = side === 1 ? "R" : "L";
    const at = (v: Vec3): Vec3 => [v[0] * side, v[1], v[2]];
    return (
      <group key={s}>
        <group position={at(G.knuckle)} name={pivot(`knuckle${s}`)}>
          {link(`knuckle${s}`)}
          <group position={at(G.finger)}>
            {link(`finger${s}`)}
            <group position={at(G.tip)} name={pivot(`tip${s}`)}>
              {link(`tip${s}`)}
              {link(`pad${s}`, 40)}
            </group>
          </group>
        </group>

        {/* Closes the four-bar. It drives nothing, exactly as in Robotiq's own
            model: its far end rides in a slot in the inner finger. */}
        <group position={at(G.innerKnuckle)} name={pivot(`innerKnuckle${s}`)}>
          {link(`innerKnuckle${s}`)}
        </group>
      </group>
    );
  };

  return (
    <group ref={root}>
      {link("base")}

      <group position={offsetBetween(null, "baseRoll")} name={pivot("baseRoll")}>
        {link("shoulder")}

        <group
          position={offsetBetween("baseRoll", "shoulderPitch")}
          name={pivot("shoulderPitch")}
        >
          {link("bicep")}

          <group
            position={offsetBetween("shoulderPitch", "elbowPitch")}
            name={pivot("elbowPitch")}
          >
            {link("forearm")}

            <group
              position={offsetBetween("elbowPitch", "wristRoll")}
              name={pivot("wristRoll")}
            >
              {link("wrist1")}

              <group
                position={offsetBetween("wristRoll", "wristPitch")}
                name={pivot("wristPitch")}
              >
                {link("wrist2")}

                <group
                  position={offsetBetween("wristPitch", "toolRoll")}
                  name={pivot("toolRoll")}
                >
                  {/* The vision module is by far the densest part of the CAD,
                      so its creases are thresholded harder to keep the line
                      count sane. */}
                  {link("tool", 32)}

                  <group position={TOOL_OFFSET} rotation={[0, GRIPPER_YAW, 0]}>
                    {link("palm", 30)}
                    {jaw(-1)}
                    {jaw(1)}
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(MODEL);
